FROM golang:1.21-alpine AS build

RUN apk add --update --no-cache \
      alpine-sdk \
      libusb-dev

WORKDIR /build

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY *.go VERSION ./
RUN go generate \
 && CGO_ENABLED=1 go build \
    -ldflags='-s -w -extldflags "-static"' \
    -o yubihsm-connector

FROM scratch AS final
COPY --from=build /build/yubihsm-connector /

ENV YUBIHSM_CONNECTOR_LISTEN=0.0.0.0:12345
ENTRYPOINT [ "/yubihsm-connector", "-d" ]
