name: "Building release binaries on MacOS"

on: [push]

jobs:
  MacOS-Build:

    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          set -e -o pipefail
          set -x
          mkdir artifact

          curl -L --max-redirs 2 -o - https://golang.org/dl/go1.17.darwin-amd64.tar.gz |\
              sudo tar xf - -C /usr/local
          export PATH=$PATH:/usr/local/go/bin:~/go/bin

          make GB_BUILD_FLAGS="-tags disable_seccomp -ldflags '-s'"
          strip -u -r bin/yubihsm-connector*
          cp bin/yubihsm-connector artifact

          ./bin/yubihsm-connector version
          ./bin/yubihsm-connector --help

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-connector-mac-amd64
          path: artifact