name: "Building release binaries on Windows"

on: [push]

jobs:
  Windows-Build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build binary
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1
          mkdir artifact

          choco install -y golang --version=1.14
          refreshenv
          go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo
          $env:Path += ";C:\Users\runneradmin\go\bin"

          go generate ./...
          go build -o bin/yubihsm-connector.exe
          cp bin/yubihsm-connector.exe artifact\

          cd resources/win-installer
          & cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat" && msbuild YubiHSMConnectorInstaller.sln /p:Configuration=Release'

          cp x64/Release/yubihsm-connector-windows-amd64.msi ../../artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubihsm-connector-windows-amd64
          path: artifact